### ISSUE TITLE
Generates error when configured in Gradle 7.4

### ISSUE THREAD

**Issue by sujaisd** [tehlers/gradle-gcs-build-cache#6]
When configuring with Gradle 7.4.2 the following error is generated

An exception occurred applying plugin request [id: 'net.idlestate.gradle-gcs-build-cache', version: '1.1.0']
> Failed to apply plugin 'net.idlestate.gradle-gcs-build-cache'.
   > class org.gradle.api.internal.project.DefaultProject_Decorated cannot be cast to class org.gradle.api.initialization.Settings (org.gradle.api.internal.project.DefaultProject_Decorated and org.gradle.api.initialization.Settings are in unnamed module of loader org.gradle.internal.classloader.VisitableURLClassLoader @7e0b37bc)

**Comment by tehlers** [comment]
Hi,

you probably followed the instructions from https://plugins.gradle.org/plugin/net.idlestate.gradle-gcs-build-cache and applied the plugin with
```
plugins {
  id "net.idlestate.gradle-gcs-build-cache" version "1.1.0"
}
```
Correct?

Since it is not a project plugin but a settings plugin this does not work and generates the error message you saw.

Unfortunately, I can't change the generated instructions of the plugin portal and have therefore added a reference to the README on Github. Take a look at the setup methods described in https://github.com/tehlers/gradle-gcs-build-cache/blob/master/README.adoc.
